server:
  port: 8502

spring:
  application:
    name: gatewayForWeb
  cloud:
    gateway:
      routes:
        - id: ForParkingLots     #路由标识，id唯一
          uri: lb://ClientParkingLots    # 路由的目标地址
          predicates:
            - Path=/ParkingLots/**
#          filters:
#            - AddRequestHeader=key,value

        - id: ForAdministrators
          uri: lb://ClientAdministrators    # 路由的目标地址
          predicates:
            - Path=/Administrators/**

      #    filters为路由过滤器  default-filters为全局过滤器  优先级按照声明顺序递增
      #    order值一样时，先执行default-filters，在执行路由过滤器，在执行，GlobalFilter

      globalcors:   #全局跨域处理
        add-to-simple-url-handler-mapping: true     #不拦截CORS的询问请求
        corsConfigurations:
          '[/**]':
            allowedOrigins: #允许哪些网站的跨域请求
              - "http://localhost:8080"
            allowedMethods: # 允许跨域的ajax请求方式
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true  #是否允许携带cookie
            maxAge: 360000    # 这次跨域检测的有效期
