server:
  port: 9003

spring:
  #  服务名称------服务名称不能使用下划线，删除下划线或者使用中划线
  application:
    name: ClientUser

  rabbitmq:
    listener:
      simple:
        prefetch: 1   #每次只能获取一条消息，处理完才能获取下一条（提升消息处理速度，避免消息堆积）
    publisher-confirm-type: correlated   #开启publisher-confirm，支持两种类型
                                          #simple同步等待confirm结果，直到超时
                                          #correlated 异步回调，定义一个ConfirmCallBack,MQ返回结果时回调ConfirmCallBack
    publisher-returns: true       #开启publisher-returns，同样是CallBack机制，不过是定义ReturnCallBack
    template:
      mandatory: true         #定义消息路由失败时策略，true则调用ReturnCallBack，false直接丢弃消息

  redis:
    lettuce:
      pool:
        max-active: 8 #最大连接，默认
        max-idle: 8 #最大空闲连接，默认
        min-idle: 0 #最小空闲连接，默认
        max-wait: 100ms #连接等待时间