server:
  port: 9000


spring:
  #  服务名称------服务名称不能使用下划线，删除下划线或者使用中划线
  application:
    name: ClientAdministrators


#指定日志级别
logging:
  level:
    com.example.administrators: info
  config: classpath:log4j2.xml


