server:
  port: 9003

spring:
  #  服务名称------服务名称不能使用下划线，删除下划线或者使用中划线
  application:
    name: ClientUser

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /   #虚拟主机
    username: guest
    password: guest


