server:
    port: 9004

spring:
    #  服务名称
    application:
        name: Provider_Vehicle
    datasource:
        url: jdbc:mysql://localhost:3306/Smart_parking_data
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
    instance:
        hostname: provider05
        #        暴露对应服务ip
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    client:
        #      注册到注册中心
        service-url:
            defaultZone: http://localhost:8651/eureka/,http://localhost:8652/eureka/
# 当输入  http://localhost:9000/actuator/shutdown就会关机
management:
    endpoints:
        web:
            exposure:
                include: shutdown
    endpoint:
        shutdown:
            enabled: true