server:
    port: 9000

spring:
#  服务名称
    application:
        name: Provider_Administrators
    datasource:
        url: jdbc:mysql://localhost:3306/Smart_parking_data
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
    instance:
        hostname: provider01
#        暴露对应服务ip
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipaddress}:${server.port}
    client:
#      注册到注册中心
        service-url:
            defaultZone: http://localhost:8651/eureka/,http://localhost:8652/eureka/
# 当输入  http://localhost:9000/actuator/shutdown就会关机
management:
  endpoints:
    web:
      exposure:
          include: shutdown
  endpoint:
    shutdown:
        enabled: true

#    #mybatis-plus配置
#    mybatis-plus:
#        #配置Mapper映射文件
#        mapper-locations: classpath:/mybatis/mappers/*.xml
#        # 配置Mybatis数据返回类型别名（默认别名为类名）
#        type-aliases-package: com.example.administrators.entity
#        configuration:
#            # 自动驼峰命名
#            # 解决连接数据库后，java的驼峰命名方式与数据库中的字段不对应的问题，比如parentId与数据库中parent_id这个字段
#            map-underscore-to-camel-case: false
