server:
  port: 8652


# 应用名称，将会显示在Eureka界面的应用名称列
  #  服务名称------服务名称不能使用下划线，删除下划线或者使用中划线

spring:
  application:
    name: EurekaServer

eureka:
  instance:
    hostname: EurekaServer01
    # 客户端在注册时使用自己的IP而不是主机名，缺省：false
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    service-url:
      # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
      # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
      defaultZone: http://localhost:8652/eureka/
      register-with-eureka: true      #是否将自己注册到注册中心，默认为true
      fetch-registry: true            #是否从注册中心获取注册信息，默认为true
    healthcheck:
      enabled: true           # 是否启用客户端健康检查